# Site settings
title: "UI Developer, UX, Interaction Architect"
author: "Boris Krone"
description: > # this means to ignore newlines until "baseurl:"
  Portolio website, Boris Krone. UI Developer, UX Aficionado. Boston.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://supergnu.com" # the base hostname & protocol for your site
github_username:  b-d-k
# port: 4001

media: "images"

gems: [jekyll-paginate]

paginate: 2
paginate_path: "/portfolio/page:num/"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

exclude: ["Gemfile","Gemfile.lock"]


  
